name: 'C++ CI'


on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4 

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libboost-test-dev -y

      - name: Configure CMake
        run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON

      - name: Build project
        run: cmake --build .

      - name: Run tests
        run: cmake --build . --target test

      - name: Display test results
        run: |
          ctest --output-on-failure || true
          cat Tests/Temporary/LastTest.log || true

   
      - name: Create package with versioned name
        run: |
          cmake --build . --target package
          
          # Если версия 0.1.0, файл станет matrix-0.1.0-Linux.deb
          mv matrix-0.1.0-Linux.deb matrix-${{ env.CPACK_PACKAGE_VERSION }}-Linux.deb

      - name: Verify package creation
        run: ls -l matrix-*

    
      - name: Create Release
        uses: actions/create-release@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         tag_name: v0.1.0     
         release_name: Release v0.1.0
         draft: false
         prerelease: false

      - name: Upload test logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ github.ref_name }}
          path: Tests/Temporary/LastTest.log

    
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
           asset_path: matrix-${{ env.CPACK_PACKAGE_VERSION }}-Linux.deb
           asset_name: matrix-${{ env.CPACK_PACKAGE_VERSION }}-Linux.deb
           asset_content_type: application/vnd.debian.binary-package

     
    
      - name: Publish Release
        id: publish-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_id: ${{ steps.create_release.outputs.id }} # Указываем ID черновика
          draft: false  # Публикуем!
          prerelease: false
